[workspace]
authors = ["jonathanle17 <jonathan.le@mrjaffesclass.com>"]
channels = ["conda-forge"]
name = "SMART-HIGHT"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
pip = "*"