apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: andre-smart-hight-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
